// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tier_list_api;

#nullable disable

namespace tier_list_api.Migrations
{
    [DbContext(typeof(TierListDbContext))]
    [Migration("20230226080444_RemovePositionalTierListItems")]
    partial class RemovePositionalTierListItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("tier_list_api.Entities.TierList", b =>
                {
                    b.Property<int>("TierListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TierListId");

                    b.ToTable("TierList");
                });

            modelBuilder.Entity("tier_list_api.Entities.TierListRow", b =>
                {
                    b.Property<int>("TierListRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TierListId")
                        .HasColumnType("int");

                    b.HasKey("TierListRowId");

                    b.HasIndex("TierListId");

                    b.ToTable("TierListRow");
                });

            modelBuilder.Entity("tier_list_api.Entities.TierListRow", b =>
                {
                    b.HasOne("tier_list_api.Entities.TierList", null)
                        .WithMany("TierListRows")
                        .HasForeignKey("TierListId");
                });

            modelBuilder.Entity("tier_list_api.Entities.TierList", b =>
                {
                    b.Navigation("TierListRows");
                });
#pragma warning restore 612, 618
        }
    }
}
