// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tier_list_api;

#nullable disable

namespace tier_list_api.Migrations
{
    [DbContext(typeof(TierListDbContext))]
    partial class TierListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("tier_list_api.Entities.PositionalTierListItem", b =>
                {
                    b.Property<int>("PositionalTierListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Label")
                        .HasColumnType("longtext");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<int>("TierListId")
                        .HasColumnType("int");

                    b.HasKey("PositionalTierListItemId");

                    b.HasIndex("TierListId");

                    b.ToTable("PositionalTierListItem");
                });

            modelBuilder.Entity("tier_list_api.Entities.TierList", b =>
                {
                    b.Property<int>("TierListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TierListId");

                    b.ToTable("TierList");
                });

            modelBuilder.Entity("tier_list_api.Entities.TierListRow", b =>
                {
                    b.Property<int>("TierListRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TierListId")
                        .HasColumnType("int");

                    b.HasKey("TierListRowId");

                    b.HasIndex("TierListId");

                    b.ToTable("TierListRow");
                });

            modelBuilder.Entity("tier_list_api.Entities.PositionalTierListItem", b =>
                {
                    b.HasOne("tier_list_api.Entities.TierList", "TierList")
                        .WithMany()
                        .HasForeignKey("TierListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TierList");
                });

            modelBuilder.Entity("tier_list_api.Entities.TierListRow", b =>
                {
                    b.HasOne("tier_list_api.Entities.TierList", null)
                        .WithMany("TierListRows")
                        .HasForeignKey("TierListId");
                });

            modelBuilder.Entity("tier_list_api.Entities.TierList", b =>
                {
                    b.Navigation("TierListRows");
                });
#pragma warning restore 612, 618
        }
    }
}
